# Generated by Django 4.0 on 2022-01-02 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspacemodel',
            name='tag',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
