# Generated by Django 4.0 on 2022-01-03 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('db_app', '0003_evaluationmodel_issuemodel_staffworkspacemodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspacemodel',
            name='user',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
