# Generated by Django 3.2.3 on 2022-01-03 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db_app', '0008_auto_20220103_0632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='staff_workspace',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='db_app.staffworkspacemodel'),
        ),
    ]
