# Generated by Django 3.2.3 on 2022-01-03 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_app', '0009_alter_taskmodel_staff_workspace'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffworkspacemodel',
            old_name='worskspace',
            new_name='workspace',
        ),
    ]
