# Generated by Django 3.2.3 on 2022-01-03 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db_app', '0011_evaluationmodel_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationmodel',
            name='task',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='db_app.taskmodel'),
        ),
    ]
