# Generated by Django 3.2.3 on 2022-01-03 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db_app', '0012_evaluationmodel_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluationmodel',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='db_app.taskmodel'),
        ),
    ]
